<?php

namespace DoctrineORMModule\Proxy\__CG__\Vendas\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Venda extends \Vendas\Entity\Venda implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'codVenda', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'dtVenda', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'dtPagamento', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'stPago', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'stAtivo', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'codCliente'];
        }

        return ['__isInitialized__', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'codVenda', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'dtVenda', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'dtPagamento', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'stPago', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'stAtivo', '' . "\0" . 'Vendas\\Entity\\Venda' . "\0" . 'codCliente'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Venda $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function toArray()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', []);

        return parent::toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function getCodVenda()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCodVenda();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodVenda', []);

        return parent::getCodVenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtVenda($dtVenda = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtVenda', [$dtVenda]);

        return parent::setDtVenda($dtVenda);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtVenda()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtVenda', []);

        return parent::getDtVenda();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtPagamento($dtPagamento = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtPagamento', [$dtPagamento]);

        return parent::setDtPagamento($dtPagamento);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtPagamento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtPagamento', []);

        return parent::getDtPagamento();
    }

    /**
     * {@inheritDoc}
     */
    public function setStPago($stPago)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStPago', [$stPago]);

        return parent::setStPago($stPago);
    }

    /**
     * {@inheritDoc}
     */
    public function getStPago()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStPago', []);

        return parent::getStPago();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', [$stAtivo]);

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', []);

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodCliente(\Vendas\Entity\Cliente $codCliente = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodCliente', [$codCliente]);

        return parent::setCodCliente($codCliente);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodCliente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodCliente', []);

        return parent::getCodCliente();
    }

    /**
     * {@inheritDoc}
     */
    public function addProdutoCodProduto(\Vendas\Entity\Produto $produtoCodProduto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProdutoCodProduto', [$produtoCodProduto]);

        return parent::addProdutoCodProduto($produtoCodProduto);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProdutoCodProduto(\Vendas\Entity\Produto $produtoCodProduto)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProdutoCodProduto', [$produtoCodProduto]);

        return parent::removeProdutoCodProduto($produtoCodProduto);
    }

    /**
     * {@inheritDoc}
     */
    public function getProdutoCodProduto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProdutoCodProduto', []);

        return parent::getProdutoCodProduto();
    }

}
