<div style="    border: solid 1px #f8f8f8;     border-radius: 10px;     padding: 5px;">
    <h2>Adicionar Venda</h2>
    <hr>
    <!--<form action="/GerenciamentoVendas/gerenciar?acao=adicionar-venda" method="post" class="form-horizontal">-->
    <?php $this->form->setAttribute('class', 'form-horizontal');?>
    <?php $this->form->setAttribute('action', $this->url('vendas').'/vendas/salvarajax');?>
    <?php echo $this->form()->openTag($this->form);?>
        <input type="hidden" name="id" value="0">
        <input type="hidden" name="entity" value="venda">

        <div class="form-group">
            <div class="col-lg-4">
                 <?php echo $this->formRow($form->get('produtoId')); ?>
            </div>
            <div class="col-lg-4">
                <?php echo $this->formRow($form->get('clienteId')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-4">
                 <?php echo $this->formRow($form->get('dtVenda')); ?>
            </div>
            <div class="col-lg-4">
                <?php echo $this->formRow($form->get('dtPagamento')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-4">
                <?php echo $this->formRow($form->get('stPago')); ?>
            </div>
        </div>

        <div class="form-group">
            <div class="col-lg-2">
                <?php echo $this->formRow($form->get('btAdicionar')); ?>
            </div>
        </div>
    <?php echo $this->form()->closeTag();?>
    <!--</form>-->
</div>

<hr>

<table class="table table-striped table-condensed" id="vendas-table">
    <thead>
        <tr>                
            <th>#</th>
            <th>Produto</th>
            <!--<th>Tipo Produto</th>-->
            <th>Cliente</th>
            <th>Data para Pagamento</th>
            <th>Data Venda</th>
            <th>Valor</th>
            <th>Empresa</th>
            <th>Produto pago?</th>
            <th></th>
        </tr>
    </thead>
    <tbody></tbody>
</table>