<div style="    border: solid 1px #f8f8f8;     border-radius: 10px;     padding: 5px;">
    <button id="mostrar-form" class="btn btn-primary" onclick="$.fn.mostrarFormAdd();" style="display: block;"><span class="glyphicon glyphicon-plus"></span> Adicionar venda</button>
    <button id="esconder-form" class="btn btn-link" onclick="$.fn.esconderFormAdd($('#vendas_form'));" style="display: none;"><span class="glyphicon glyphicon-arrow-left"></span></button>
    <div id="form-add-container" style="display: none;">
        <h3>Adicionar Venda</h3>
        <!--<form action="/GerenciamentoVendas/gerenciar?acao=adicionar-venda" method="post" class="form-horizontal">-->
        <?php $this->form->setAttribute('class', 'form-horizontal'); ?>
        <?php $this->form->setAttribute('action', $this->url('vendas') . '/salvarajax'); ?>
        <?php echo $this->form()->openTag($this->form); ?>
        <input type="hidden" name="id" value="0">
        <?php echo $this->formRow($form->get('codVenda')); ?>
        <!--<input type="hidden" name="entity" value="venda">-->

        <div id="produtos">
            <div class="form-group" id="produto-1">
                <div class="col-lg-3">
                    <?php echo $this->formRow($form->get('codProduto-1')); ?>
                </div>
                <div class="col-lg-3">
                    <?php echo $this->formLabel($form->get('precoPago-1')); ?>
                    <div class="input-group">
                        <div class="input-group-addon">R$</div>
                        <?php echo $this->formElement($form->get('precoPago-1')); ?>
                    </div>
                </div>
                <div class="col-lg-3">
                    <?php echo $this->formRow($form->get('quantidade-1')); ?>
                </div>
                <div class="col-lg-2">
                    <?php echo $this->formLabel($form->get('desconto-1')); ?>
                    <div class="input-group">
                        <div class="input-group-addon"><strong>%</strong></div>
                        <?php echo $this->formElement($form->get('desconto-1')); ?>
                    </div>
                </div>
                <div class="col-lg-1">
                    <div class="input-group" style="margin-top:20px;">
                        <button class="btn btn-success" type="button" onclick="$.fn.addProdutoVenda();"><span class="glyphicon glyphicon-plus"></span></button>
                    </div>
                </div>
            </div>
        </div>
        <!-- <div class="form-group"></div> -->
        <hr>
        <div class="form-group">
            <div class="col-lg-4">
                <?php echo $this->formLabel($form->get('dtVenda')); ?>
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
                    <?php echo $this->formElement($form->get('dtVenda')); ?>
                </div>
            </div>
            <div class="col-lg-4">
                <?php echo $this->formLabel($form->get('dtPagamento')); ?>
                <div class="input-group">
                    <div class="input-group-addon"><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span></div>
                    <?php echo $this->formElement($form->get('dtPagamento')); ?>
                </div>
            </div>
            <div class="col-lg-4">
                <?php echo $this->formRow($form->get('stPago')); ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <div class="col-lg-4">
                <?php echo $this->formRow($form->get('codCliente')); ?>
            </div>
        </div>
        <hr>
        <div class="form-group">
            <div class="col-lg-2">
                <?php echo $this->formRow($form->get('btCancelar')); ?>
                <?php echo $this->formRow($form->get('btAdicionar')); ?>
            </div>
        </div>
        <span class="glyphicon glyphicon-info-sign" style="color:#296294;"></span><span class="text-info"> - Os campos com asterisco (*) são obrigatórios.</span>
        <?php echo $this->form()->closeTag(); ?>
    </div>
    <!--</form>-->
    <hr>
    <h3 id="listagem">Listagem de Vendas</h3>
    <table class="table table-striped table-condensed" id="vendas-table">
        <thead>
            <tr>                
                <th>#</th>
                <th>Produto</th>
                <th>Valor da Venda</th>
                <th>Valor sem desconto</th>
                <th>Desconto</th>
                <th>Quantidade</th>
                <th>Cliente</th>
                <th>Data para Pagamento</th>
                <th>Data Venda</th>
                <th>Empresa</th>
                <th>Pago?</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>